# shell-runner configuration

# prepare gitlab-ci
before_script:
- "[ ! type docker-php-ext-install >/dev/null 2>&1 ] && ( apt-get -y -q update; apt-get -y -q upgrade; apt-get -y -q install git unzip libicu-dev; docker-php-ext-install intl; )"
- php -v
- curl -sS https://getcomposer.org/installer | php
- php composer.phar --version
- php -d memory_limit=-1 composer.phar install

# define types/stages
types:
- test

test-php56_job:
  type: test
  image: php:5.6
  script:
  - php -d memory_limit=-1 ./vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
  allow_failure: false

test-php70_job:
  type: test
  image: php:7.0
  script:
  - php -d memory_limit=-1 ./vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
  allow_failure: false


